name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: release-pentest-build

jobs:
  build:
    name: Run Pentest Release build
    runs-on: ubuntu-latest
    steps:
      - name: Set input to VAR and print VAW
        run: 'echo "Triggered event text: ${{ github.event.client_payload.var }}"'
